In [5]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine

In [7]:
wine = load_wine()

In [8]:
X = wine['data']

In [9]:
X.shape

(178, 13)

**Step 1**

In [14]:
mu = X.mean(axis=0)
X_ = (X - mu)
X_.shape

(178, 13)

**Step 2**

In [16]:
S = np.dot(X_.T, X_)
S.shape

(13, 13)

**Step 3**

In [19]:
lambdas, vectors = np.linalg.eig(S)

In [20]:
lambdas.shape

(13,)

In [21]:
lambdas[:2]

array([17558716.7445941 ,    30538.74216659])

In [22]:
vectors.shape

(13, 13)

**Step 4**

In [23]:
V = vectors[:, :2]
V.shape

(13, 2)

**Projection**

In [24]:
X_.shape

(178, 13)

In [25]:
V.shape

(13, 2)

In [27]:
X_new = np.dot(X_, V)
X_new.shape

(178, 2)

In [33]:
X_new[:5]

array([[-3.18562979e+02, -2.14921307e+01],
       [-3.03097420e+02,  5.36471768e+00],
       [-4.38061133e+02,  6.53730945e+00],
       [-7.33240139e+02, -1.92729032e-01],
       [ 1.15714285e+01, -1.84899946e+01]])

**Sklearn**

In [29]:
from sklearn.decomposition import PCA

In [30]:
pca = PCA(n_components=2)

In [35]:
skX_ = pca.fit_transform(X)
skX_.shape

(178, 2)

In [36]:
skX_[:5]

array([[ 3.18562979e+02,  2.14921307e+01],
       [ 3.03097420e+02, -5.36471768e+00],
       [ 4.38061133e+02, -6.53730945e+00],
       [ 7.33240139e+02,  1.92729032e-01],
       [-1.15714285e+01,  1.84899946e+01]])

In [38]:
np.allclose(X_new, -skX_)

True